# Generated by Django 5.1.4 on 2024-12-14 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('synopsis', models.TextField()),
                ('image', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('synopsis', models.TextField()),
                ('duration_secs', models.DurationField()),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='static/images/')),
                ('pud_date', models.DateTimeField(verbose_name='Date Published')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_app1.series')),
            ],
        ),
    ]
